sudo: false
language: node_js
node_js:
  - "4"
  - "6"
  - "7"
script: npm run travis
before_script:
  - npm i -g yarn@1.19.1
after_success: cat ./coverage/lcov.info | node_modules/.bin/coveralls --verbose && rm -rf ./coverage
