sudo: false
language: node_js
node_js:
  - "4"
  - "6"
  - "7"
script: npm run travis
before_install:
  - curl -o- -L -k https://yarnpkg.com/install.sh | bash -s -- --version 1.22.0
after_success: cat ./coverage/lcov.info | node_modules/.bin/coveralls --verbose && rm -rf ./coverage
